### PR TITLE
enable creditable pay on txtTreatmentID_TextChanged - fix #4

### LINKED ISSUE #4: Kalo mau DP masukinnya gimana?
How to input DP?

Current: it's supposed to be inputted directly if it's creditable

let's just investigate this first and see if it's working

### PR DESCRIPTION
**Pull request by CyberKasumi**
@IvanHalimP please review. the fix is described in the title.

### CODE REVIEW

**Comment by IvanHalimP** [comment]
me still not understand what happened...
*me haven't switch fully to KGAM mode maybe...
but, what happened?

**Comment by CyberKasumi** [comment]
so, the case is:
if the treatment is inputted via searchtreatment form, it is ok
but, if the treatment is inputted by entering treatment ID, none can be credited (isCredited not set)

**Comment by CyberKasumi** [comment]
so what i do is add a query for getIsCreditable status, and if one is creditable, the whole payment is creditable

**Comment by IvanHalimP** [comment]
wait"
ini me musti review dulu ya
walao weh...

**Pull request merged**
